version: '3'
services:
  backend:
    build:
      context: backend
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: thisisunsafe
      MYSQL_DATABASE: openpager 
      MYSQL_USER: goserver
      MYSQL_PASSWORD: thisisunsafe
    ports:
      - "3306:3306"
