version: '3'
services:
  backend:
    container_name: goauth_app
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
        - goauthnetwork
  db:
    image: mysql:8.0
    container_name: goauth_mysql
    environment:
      MYSQL_ROOT_PASSWORD: thisisunsafe
      MYSQL_DATABASE: goauth 
      MYSQL_USER: goserver
      MYSQL_PASSWORD: thisisunsafe
    ports:
      - "3306:3306"
    networks:
        - goauthnetwork
networks:
  goauthnetwork:
